/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CarbonHelp: typeof import('~icons/carbon/help')['default']
    Choice: typeof import('./src/components/Choice.vue')['default']
    Game: typeof import('./src/components/game/Game.vue')['default']
    GameButtons: typeof import('./src/components/game/GameButtons.vue')['default']
    GameCard: typeof import('./src/components/game/GameCard.vue')['default']
    GameCards: typeof import('./src/components/game/GameCards.vue')['default']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HeaderSwitch: typeof import('./src/components/header/HeaderSwitch.vue')['default']
    MdiClose: typeof import('~icons/mdi/close')['default']
    MdiRefresh: typeof import('~icons/mdi/refresh')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
