/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Btns: typeof import('./src/components/game/Btns.vue')['default']
    CarbonHelp: typeof import('~icons/carbon/help')['default']
    Card: typeof import('./src/components/game/Card.vue')['default']
    Cards: typeof import('./src/components/game/Cards.vue')['default']
    Choice: typeof import('./src/components/Choice.vue')['default']
    Game: typeof import('./src/components/game/Game.vue')['default']
    MdiClose: typeof import('~icons/mdi/close')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
